const constants = {
   SET_CURRENTUSER : "SET_CURRENTUSER",
   CLEAR_CURRENTUSER: "CLEAR",
   SET_SEARCHRESULTS: "SET_SEARCHRESULTS",
   SET_DETAILRESULTS: "SET_DETAILRESULTS",
   SET_CITYDATA: "SET_CITYDATA",
   SET_SEARCHDATES: "SET_SEARCHDATES",
   SET_SELECTEDHOTEL: "SET_SELECTEDHOTEL",
   ADD_BOOKING: "ADD_BOOKING",
   CANCEL_BOOKING: "CANCEL_BOOKING",
   UPDATE_BOOKING: "UPDATE_BOOKING",
   CANCELALL_BOOKING: "CANCELALL_BOOKING",
   ADD_REWARD: "ADD_REWARD",
   REDEEM_REWARD:"REDEEM_REWARD",
   SET_SELECTED_HOTEL_CLIENT_PRICE: "SET_SELECTED_HOTEL_CLIENT_PRICE"
 }

 export default constants
