const constants = {
   SET_CURRENTUSER : "SET_CURRENTUSER",
   CLEAR_CURRENTUSER: "CLEAR",
   SET_SEARCHRESULTS: "SET_SEARCHRESULTS",
   SET_DETAILRESULTS: "SET_DETAILRESULTS",
   SET_CITYDATA: "SET_CITYDATA",
   SET_SEARCHDATES: "SET_SEARCHDATES",
   SET_SELECTEDHOTEL: "SET_SELECTEDHOTEL",
   ADD_BOOKING: "ADD_BOOKING",
   CANCEL_BOOKING: "CANCEL_BOOKING",
   UPDATE_BOOKING: "UPDATE_BOOKING",
   CANCELALL_BOOKING: "CANCELALL_BOOKING"
 }

 export default constants
